2018-07-24 21:48:11,505 [ INFO] werkzeug [_log]
2018-07-24 21:48:11,507 [ INFO] werkzeug [_log]
2018-07-24 21:48:12,747 [ WARNING] werkzeug [_log]
2018-07-24 21:48:12,748 [ INFO] werkzeug [_log]
2018-07-24 21:49:37,829 [ INFO] werkzeug [_log]
2018-07-24 21:49:37,965 [ INFO] werkzeug [_log]
2018-07-24 21:49:39,295 [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
2018-07-24 21:49:39,296 [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
2018-07-24 21:50:35,992 [ INFO] werkzeug [_log] [_internal.py, 87  * Detected change in '/home/developer/Documentos/dashboard4/app.py', reloading
2018-07-24 21:50:36,130 [ INFO] werkzeug [_log]
[24/07/18 21:51:21] [ INFO] werkzeug [_log] [_internal.py, 87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[24/07/18 21:51:21] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:51:22] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:51:22] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:51:47] [ INFO] werkzeug [_log] [_internal.py, 87  * Detected change in '/home/developer/Documentos/dashboard4/app.py', reloading
[24/07/18 21:51:47] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:51:48] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:51:48] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:52:14] [ INFO] werkzeug [_log] [_internal.py, 87  * Detected change in '/home/developer/Documentos/dashboard4/app.py', reloading
[24/07/18 21:52:15] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:52:16] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:52:16] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:52:17] [ INFO] werkzeug [_log] [_internal.py, 87  * Detected change in '/home/developer/Documentos/dashboard4/app.py', reloading
[24/07/18 21:52:17] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:52:19] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:52:19] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:52:33] [ INFO] werkzeug [_log] [_internal.py, 87  * Detected change in '/home/developer/Documentos/dashboard4/app.py', reloading
[24/07/18 21:52:33] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:52:35] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:52:35] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:52:40] [ INFO] werkzeug [_log] [_internal.py, 87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[24/07/18 21:52:40] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:52:42] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:52:42] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:53:02] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:02] "GET / HTTP/1.1" 500 -
[24/07/18 21:53:03] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:03] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[24/07/18 21:53:03] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:03] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:03] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:03] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[24/07/18 21:53:03] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:03] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[24/07/18 21:53:03] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:03] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:05] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:05] "GET / HTTP/1.1" 500 -
[24/07/18 21:53:05] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:05] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[24/07/18 21:53:05] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:05] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[24/07/18 21:53:05] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:05] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[24/07/18 21:53:05] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:05] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:05] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:05] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:07] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:07] "GET /jenkins HTTP/1.1" 302 -
[24/07/18 21:53:07] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:07] "GET / HTTP/1.1" 500 -
[24/07/18 21:53:07] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:07] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[24/07/18 21:53:07] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:07] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[24/07/18 21:53:07] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:07] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[24/07/18 21:53:07] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:07] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:07] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:07] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:14] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:14] "GET /docker HTTP/1.1" 302 -
[24/07/18 21:53:14] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:14] "GET / HTTP/1.1" 500 -
[24/07/18 21:53:14] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:14] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[24/07/18 21:53:14] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:14] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[24/07/18 21:53:14] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:14] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[24/07/18 21:53:14] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:14] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:14] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:53:14] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[24/07/18 21:53:47] [ INFO] werkzeug [_log] [_internal.py, 87  * Detected change in '/home/developer/Documentos/dashboard4/app.py', reloading
[24/07/18 21:53:47] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:53:50] [ INFO] werkzeug [_log] [_internal.py, 87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[24/07/18 21:53:50] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:53:52] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:53:52] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:54:01] [ INFO] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 21:54:01] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:01] "GET / HTTP/1.1" 200 -
[24/07/18 21:54:08] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:08] "POST /login HTTP/1.1" 302 -
[24/07/18 21:54:08] [ DEBUG] urllib3.connectionpool [_new_conn] [connectionpool.py, 205 Starting new HTTP connection (1): 192.168.0.200:2376
[24/07/18 21:54:08] [ DEBUG] urllib3.connectionpool [_make_request] [connectionpool.py, 393 http://192.168.0.200:2376 "GET /v1.35/containers/flask-app/json HTTP/1.1" 200 None
[24/07/18 21:54:08] [ DEBUG] urllib3.connectionpool [_make_request] [connectionpool.py, 393 http://192.168.0.200:2376 "GET /v1.35/images/b8ce4cf284016bf0c5a0113a7572763531fa086d4b7e8f2794b45db2b962c1ba/json HTTP/1.1" 200 None
[24/07/18 21:54:08] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:08] "GET /docker HTTP/1.1" 200 -
[24/07/18 21:54:46] [ DEBUG] urllib3.connectionpool [_make_request] [connectionpool.py, 393 http://192.168.0.200:2376 "GET /v1.35/containers/flask-app/json HTTP/1.1" 200 None
[24/07/18 21:54:46] [ DEBUG] urllib3.connectionpool [_make_request] [connectionpool.py, 393 http://192.168.0.200:2376 "GET /v1.35/images/b8ce4cf284016bf0c5a0113a7572763531fa086d4b7e8f2794b45db2b962c1ba/json HTTP/1.1" 200 None
[24/07/18 21:54:46] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:46] "GET /docker HTTP/1.1" 200 -
[24/07/18 21:54:47] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:47] "GET /logoff HTTP/1.1" 302 -
[24/07/18 21:54:47] [ INFO] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 21:54:47] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:47] "GET / HTTP/1.1" 200 -
[24/07/18 21:54:56] [ WARNING] root [login] [app.py, 42 autenticação invalida
[24/07/18 21:54:56] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:56] "POST /login HTTP/1.1" 302 -
[24/07/18 21:54:56] [ INFO] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 21:54:56] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:54:56] "GET / HTTP/1.1" 200 -
[24/07/18 21:55:01] [ WARNING] root [login] [app.py, 42 autenticação invalida
[24/07/18 21:55:01] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:55:01] "POST /login HTTP/1.1" 302 -
[24/07/18 21:55:01] [ INFO] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 21:55:01] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:55:01] "GET / HTTP/1.1" 200 -
[24/07/18 21:56:03] [ INFO] werkzeug [_log] [_internal.py, 87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[24/07/18 21:56:03] [ INFO] werkzeug [_log] [_internal.py, 87  * Restarting with stat
[24/07/18 21:56:05] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:56:05] [ INFO] werkzeug [_log] [_internal.py, 87  * Debugger pin code: 116-651-338
[24/07/18 21:56:05] [ INFO] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 21:56:05] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:56:05] "GET / HTTP/1.1" 200 -
[24/07/18 21:56:09] [ WARNING] root [login] [app.py, 42 autenticação invalida
[24/07/18 21:56:09] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:56:09] "POST /login HTTP/1.1" 302 -
[24/07/18 21:56:09] [ INFO] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 21:56:09] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:56:09] "GET / HTTP/1.1" 200 -
[24/07/18 21:56:12] [ WARNING] root [login] [app.py, 42 autenticação invalida
[24/07/18 21:56:12] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:56:12] "POST /login HTTP/1.1" 302 -
[24/07/18 21:56:12] [ INFO] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 21:56:12] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:56:12] "GET / HTTP/1.1" 200 -
[24/07/18 21:56:21] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:56:21] "POST /login HTTP/1.1" 302 -
[24/07/18 21:56:21] [ DEBUG] urllib3.connectionpool [_new_conn] [connectionpool.py, 205 Starting new HTTP connection (1): 192.168.0.200:2376
[24/07/18 21:56:21] [ DEBUG] urllib3.connectionpool [_make_request] [connectionpool.py, 393 http://192.168.0.200:2376 "GET /v1.35/containers/flask-app/json HTTP/1.1" 200 None
[24/07/18 21:56:21] [ DEBUG] urllib3.connectionpool [_make_request] [connectionpool.py, 393 http://192.168.0.200:2376 "GET /v1.35/images/b8ce4cf284016bf0c5a0113a7572763531fa086d4b7e8f2794b45db2b962c1ba/json HTTP/1.1" 200 None
[24/07/18 21:56:21] [ INFO] werkzeug [_log] [_internal.py, 87 127.0.0.1 - - [24/Jul/2018 21:56:21] "GET /docker HTTP/1.1" 200 -
[24/07/18 21:58:55] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 21:59:19] [ WARNING] root [login] [app.py, 42 autenticação invalida
[24/07/18 22:00:34] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 22:00:35] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:00:42] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:00:43] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:00:44] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:00:48] [ WARNING] root [login] [app.py, 42 autenticação invalida
[24/07/18 22:00:49] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:03:16] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 22:03:19] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:03:22] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:03:30] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 22:03:36] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:03:37] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:03:38] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:03:38] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:04:37] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 22:04:41] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[24/07/18 22:04:48] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 22:05:15] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[24/07/18 22:05:15] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:29:08] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 18:29:55] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:30:00] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:30:02] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:30:03] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:30:04] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:30:05] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:30:09] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:33:20] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:33:20] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 18:33:24] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 18:33:39] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 18:42:09] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 19:39:05] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 19:39:06] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 19:39:08] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 19:39:09] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 19:39:10] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 21:11:05] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 21:11:09] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 21:11:20] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 21:13:26] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 21:49:16] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 21:50:42] [ WARNING] werkzeug [_log] [_internal.py, 87  * Debugger is active!
[25/07/18 21:50:45] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[25/07/18 21:50:48] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:10:55] [ INFO] werkzeug [_log] [_internal.py, 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[30/12/19 19:10:55] [ INFO] werkzeug [_log] [_internal.py, 122  * Restarting with stat
[30/12/19 19:10:55] [ WARNING] werkzeug [_log] [_internal.py, 122  * Debugger is active!
[30/12/19 19:10:55] [ INFO] werkzeug [_log] [_internal.py, 122  * Debugger PIN: 819-424-632
[30/12/19 19:11:05] [ INFO] werkzeug [_log] [_internal.py, 122  * Detected change in '/home/thiago/Documentos/cursos/dashboard-flask/app.py', reloading
[30/12/19 19:11:05] [ INFO] werkzeug [_log] [_internal.py, 122  * Restarting with stat
[30/12/19 19:11:08] [ INFO] werkzeug [_log] [_internal.py, 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[30/12/19 19:11:13] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:11:13] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:11:13] "GET / HTTP/1.1" 200 -
[30/12/19 19:11:20] [ ERROR] app [log_exception] [app.py, 1891 Exception on /login [POST]
Traceback (most recent call last):
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 38, in login
    if ldap.bind():
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/ldap3/core/connection.py", line 531, in bind
    self.open(read_server_info=False)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/ldap3/strategy/base.py", line 146, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket connection error while opening: [Errno 113] No route to host'), ('192.168.0.200', 389))])
[30/12/19 19:11:20] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:11:20] "POST /login HTTP/1.1" 500 -
[30/12/19 19:12:01] [ ERROR] app [log_exception] [app.py, 1891 Exception on /gitlab [GET]
Traceback (most recent call last):
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thiago/Documentos/cursos/dashboard-flask/blueprints/gitlab.py", line 12, in home
    users = requests.get(GITLAB.format(tk = TOKEN, route = 'users'))
NameError: name 'requests' is not defined
[30/12/19 19:12:01] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:01] "GET /gitlab HTTP/1.1" 500 -
[30/12/19 19:12:03] [ WARNING] app [home] [pocker.py, 12 Acesso não autorizado
[30/12/19 19:12:03] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:03] "GET /docker HTTP/1.1" 302 -
[30/12/19 19:12:03] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:03] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:03] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:04] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:04] "GET /jenkins HTTP/1.1" 404 -
[30/12/19 19:12:07] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:07] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:07] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:07] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:07] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:07] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:07] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:07] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:07] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:07] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:07] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:07] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:08] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:08] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:08] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:08] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:08] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:08] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:15] [ ERROR] app [log_exception] [app.py, 1891 Exception on /login [POST]
Traceback (most recent call last):
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 38, in login
    if ldap.bind():
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/ldap3/core/connection.py", line 531, in bind
    self.open(read_server_info=False)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/home/thiago/Documentos/cursos/dashboard-flask/venv/lib/python3.7/site-packages/ldap3/strategy/base.py", line 146, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket connection error while opening: [Errno 113] No route to host'), ('192.168.0.200', 389))])
[30/12/19 19:12:15] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:15] "POST /login HTTP/1.1" 500 -
[30/12/19 19:12:25] [ INFO] werkzeug [_log] [_internal.py, 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[30/12/19 19:12:25] [ INFO] werkzeug [_log] [_internal.py, 122  * Restarting with stat
[30/12/19 19:12:25] [ WARNING] werkzeug [_log] [_internal.py, 122  * Debugger is active!
[30/12/19 19:12:25] [ INFO] werkzeug [_log] [_internal.py, 122  * Debugger PIN: 819-424-632
[30/12/19 19:12:26] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:26] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:26] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:27] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:27] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:27] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:27] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:27] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:27] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:27] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:27] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:27] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:27] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:27] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:27] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:34] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:34] "GET /jenkins HTTP/1.1" 404 -
[30/12/19 19:12:36] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:36] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:36] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:37] [ WARNING] app [home] [pocker.py, 12 Acesso não autorizado
[30/12/19 19:12:37] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:37] "GET /docker HTTP/1.1" 302 -
[30/12/19 19:12:37] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:37] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:37] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:38] [ WARNING] app [home] [pocker.py, 12 Acesso não autorizado
[30/12/19 19:12:38] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:38] "GET /docker HTTP/1.1" 302 -
[30/12/19 19:12:38] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:38] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:38] "GET / HTTP/1.1" 200 -
[30/12/19 19:12:38] [ WARNING] app [home] [pocker.py, 12 Acesso não autorizado
[30/12/19 19:12:38] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:38] "GET /docker HTTP/1.1" 302 -
[30/12/19 19:12:38] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:12:38] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:12:38] "GET / HTTP/1.1" 200 -
[30/12/19 19:16:24] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:16:24] "POST /login HTTP/1.1" 500 -
[30/12/19 19:16:24] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:16:24] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[30/12/19 19:16:24] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:16:24] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[30/12/19 19:16:24] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:16:24] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[30/12/19 19:16:24] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:16:24] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[30/12/19 19:16:24] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:16:24] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[30/12/19 19:17:43] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:43] "GET /logoff HTTP/1.1" 302 -
[30/12/19 19:17:43] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:17:43] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:43] "GET / HTTP/1.1" 200 -
[30/12/19 19:17:44] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:44] "GET /logoff HTTP/1.1" 302 -
[30/12/19 19:17:44] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:17:44] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:44] "GET / HTTP/1.1" 200 -
[30/12/19 19:17:44] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:44] "GET /logoff HTTP/1.1" 302 -
[30/12/19 19:17:44] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:17:44] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:44] "GET / HTTP/1.1" 200 -
[30/12/19 19:17:44] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:44] "GET /logoff HTTP/1.1" 302 -
[30/12/19 19:17:44] [ ERROR] root [home] [app.py, 27 Acessaram o dashboard
[30/12/19 19:17:44] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:17:44] "GET / HTTP/1.1" 200 -
[30/12/19 19:19:57] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:19:57] "POST /login HTTP/1.1" 500 -
[30/12/19 19:19:57] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:19:57] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[30/12/19 19:19:57] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:19:57] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[30/12/19 19:19:57] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:19:57] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[30/12/19 19:19:58] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:19:58] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[30/12/19 19:21:30] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:21:30] "POST /login HTTP/1.1" 500 -
[30/12/19 19:21:30] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:21:30] "POST /login HTTP/1.1" 500 -
[30/12/19 19:21:30] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:21:30] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[30/12/19 19:21:30] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:21:30] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[30/12/19 19:21:30] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:21:30] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[30/12/19 19:21:30] [ INFO] werkzeug [_log] [_internal.py, 122 127.0.0.1 - - [30/Dec/2019 19:21:30] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[30/12/19 19:21:43] [ INFO] werkzeug [_log] [_internal.py, 122  * Detected change in '/home/thiago/Documentos/cursos/dashboard-flask/app.py', reloading
[30/12/19 19:21:43] [ INFO] werkzeug [_log] [_internal.py, 122  * Restarting with stat
[30/12/19 19:22:32] [ INFO] werkzeug [_log] [_internal.py, 122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
